/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSessionLogsRouteImport } from './routes/_app.session-logs'
import { Route as AppScheduleGeneratorRouteImport } from './routes/_app.schedule-generator'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppRoomReservationRouteImport } from './routes/_app.room-reservation'
import { Route as AppRoomOccupancyRouteImport } from './routes/_app.room-occupancy'
import { Route as AppReservationRequestsRouteImport } from './routes/_app.reservation-requests'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppFacultyMonitorRouteImport } from './routes/_app.faculty-monitor'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionLogsRoute = AppSessionLogsRouteImport.update({
  id: '/session-logs',
  path: '/session-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleGeneratorRoute = AppScheduleGeneratorRouteImport.update({
  id: '/schedule-generator',
  path: '/schedule-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomReservationRoute = AppRoomReservationRouteImport.update({
  id: '/room-reservation',
  path: '/room-reservation',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomOccupancyRoute = AppRoomOccupancyRouteImport.update({
  id: '/room-occupancy',
  path: '/room-occupancy',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationRequestsRoute = AppReservationRequestsRouteImport.update({
  id: '/reservation-requests',
  path: '/reservation-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultyMonitorRoute = AppFacultyMonitorRouteImport.update({
  id: '/faculty-monitor',
  path: '/faculty-monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/faculty-monitor': typeof AppFacultyMonitorRoute
  '/notifications': typeof AppNotificationsRoute
  '/reservation-requests': typeof AppReservationRequestsRoute
  '/room-occupancy': typeof AppRoomOccupancyRoute
  '/room-reservation': typeof AppRoomReservationRoute
  '/schedule': typeof AppScheduleRoute
  '/schedule-generator': typeof AppScheduleGeneratorRoute
  '/session-logs': typeof AppSessionLogsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/faculty-monitor': typeof AppFacultyMonitorRoute
  '/notifications': typeof AppNotificationsRoute
  '/reservation-requests': typeof AppReservationRequestsRoute
  '/room-occupancy': typeof AppRoomOccupancyRoute
  '/room-reservation': typeof AppRoomReservationRoute
  '/schedule': typeof AppScheduleRoute
  '/schedule-generator': typeof AppScheduleGeneratorRoute
  '/session-logs': typeof AppSessionLogsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/faculty-monitor': typeof AppFacultyMonitorRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reservation-requests': typeof AppReservationRequestsRoute
  '/_app/room-occupancy': typeof AppRoomOccupancyRoute
  '/_app/room-reservation': typeof AppRoomReservationRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/schedule-generator': typeof AppScheduleGeneratorRoute
  '/_app/session-logs': typeof AppSessionLogsRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/faculty-monitor'
    | '/notifications'
    | '/reservation-requests'
    | '/room-occupancy'
    | '/room-reservation'
    | '/schedule'
    | '/schedule-generator'
    | '/session-logs'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/faculty-monitor'
    | '/notifications'
    | '/reservation-requests'
    | '/room-occupancy'
    | '/room-reservation'
    | '/schedule'
    | '/schedule-generator'
    | '/session-logs'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/faculty-monitor'
    | '/_app/notifications'
    | '/_app/reservation-requests'
    | '/_app/room-occupancy'
    | '/_app/room-reservation'
    | '/_app/schedule'
    | '/_app/schedule-generator'
    | '/_app/session-logs'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session-logs': {
      id: '/_app/session-logs'
      path: '/session-logs'
      fullPath: '/session-logs'
      preLoaderRoute: typeof AppSessionLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule-generator': {
      id: '/_app/schedule-generator'
      path: '/schedule-generator'
      fullPath: '/schedule-generator'
      preLoaderRoute: typeof AppScheduleGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/room-reservation': {
      id: '/_app/room-reservation'
      path: '/room-reservation'
      fullPath: '/room-reservation'
      preLoaderRoute: typeof AppRoomReservationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/room-occupancy': {
      id: '/_app/room-occupancy'
      path: '/room-occupancy'
      fullPath: '/room-occupancy'
      preLoaderRoute: typeof AppRoomOccupancyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservation-requests': {
      id: '/_app/reservation-requests'
      path: '/reservation-requests'
      fullPath: '/reservation-requests'
      preLoaderRoute: typeof AppReservationRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faculty-monitor': {
      id: '/_app/faculty-monitor'
      path: '/faculty-monitor'
      fullPath: '/faculty-monitor'
      preLoaderRoute: typeof AppFacultyMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFacultyMonitorRoute: typeof AppFacultyMonitorRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReservationRequestsRoute: typeof AppReservationRequestsRoute
  AppRoomOccupancyRoute: typeof AppRoomOccupancyRoute
  AppRoomReservationRoute: typeof AppRoomReservationRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppScheduleGeneratorRoute: typeof AppScheduleGeneratorRoute
  AppSessionLogsRoute: typeof AppSessionLogsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFacultyMonitorRoute: AppFacultyMonitorRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReservationRequestsRoute: AppReservationRequestsRoute,
  AppRoomOccupancyRoute: AppRoomOccupancyRoute,
  AppRoomReservationRoute: AppRoomReservationRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppScheduleGeneratorRoute: AppScheduleGeneratorRoute,
  AppSessionLogsRoute: AppSessionLogsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
